export interface CategoryOdata{
    searchType: string,
    pageSize: number,
    pagePass: number,
    searchValue: string,
    price: string,
    date: string,
    startDate: string,
    endDate: string,
    calorie: string,
    tag: string,
    difficulty: string,
    bodyFocus: string,
    sort: string,
    name: string,
    isFirstTime: boolean,
}